In [2]:
import pandas as pd

file = 'mower_market_snapshot.csv'

df = pd.read_csv(file, delimiter=";")
df

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [ ]:
#Exo 2
series = pd.Series([1,2,np.nan, 4])
series

df = pd.DataFrame(np.array([1,2,3,4,5,6]).reshape(2,3))
df

df = pd.DataFrame(np.array([1,2,3,4,5,6]).reshape(2,3),
columns=list('ABC'), index=list('XY'))
df

df.isnull()


df2 = df.copy() 
df2

df.drop_duplicates()

df.groupby('capacity').sum() 

df.tail(10)

df.head(10)

df.drop(columns=['capacity', 'id'])

df.drop([2, 1200])

df.filter(items=['capacity', 'id'])

df.get("id")

df.sort_index(ascending=False)

df.loc[:, 'product_type'] = "essence"
df

In [6]:
#EXO 3 

def describeColumn(dataFrame,columnName):
    print(dataFrame[columnName].describe())
    
describeColumn(df,'prod_cost')

count     1381
unique    1333
top          0
freq        20
Name: prod_cost, dtype: object

In [55]:
#Exo 4
def missingValueByColumn(dataFrame):
    null_columns=dataFrame.columns[dataFrame.isnull().any()]
    print(dataFrame[null_columns].isnull().sum())

missingValueByColumn(df)

auto-portee    1257
electrique      986
essence         555
dtype: int64

In [35]:
#Exo 5
def replaceMissingValue(dataFrame,columnName):
    values=dataFrame[columnName].mean
    dataFrame[columnName].apply(pd.to_numeric, errors='coerce')
    dataFrame.fillna(value=values, inplace=True)
    return dataFrame

replaceMissingValue(df,'prod_cost')

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [36]:
#Exo 6
def uniqueValue(dataFrame,columnName):
    return dataFrame[columnName].unique()

uniqueValue(df,'warranty')

array(['3ans', '3 ans.', '3_ans', '3 anss', '3ans.', '3 ans', '3_ans.',
       '3_anss', '3anss', '2 ans', '2 anss', '2anss', '2_ans', '2ans',
       '2_ans.', '2 ans.', '2_anss', '2ans.', '1 an', '1an', '1_an.',
       '1ans', '1an.', '1_ans', '1_an', '1 an.', '1 ans'], dtype=object)

In [53]:
#Exo 7,8
def numericValue(dataFrame,columnName):
    return dataFrame[columnName].str[0].unique()

numericValue(df,'warranty')

array(['3', '2', '1'], dtype=object)

In [52]:
#Exo 9
def subCategory(dataFrame, column, values):
    for i in range (len(dataFrame)):
            if type(dataFrame.loc[i, column]) != str :
                if dataFrame.loc[i, column] < 300 :
                    dataFrame.loc[i, column] = values[0]
                elif dataFrame.loc[i, column] > 300 and dataFrame.loc[i, column] < 500 :
                    dataFrame.loc[i, column] = values[1]
                else :
                    dataFrame.loc[i, column] = values[2]
      
    
values = ['0-300', '301-500', '501++']
subCategory(df, 'price', values)
df

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness,auto-portee,electrique,essence
0,10.492623,0.042528,18377,633.766584,501++,195.03551928211797,1,Low,3ans,0.006360,0.650648,1.0,NaN,NaN
1,20.273730,0.037896,19363,731.576817,501++,151.31809934886763,1,Low,3 ans.,0.006840,0.699792,1.0,NaN,NaN
2,20.190457,0.039111,19641,741.218202,501++,178.13731921134948,1,Low,3_ans,0.006179,0.632129,1.0,NaN,NaN
3,27.220131,0.041303,18728,654.255635,501++,162.82946157588628,1,Low,3 anss,0.007925,0.810730,1.0,NaN,NaN
4,16.370911,0.037938,18722,703.094527,501++,141.48693796090603,1,Medium,3ans.,0.007406,0.757614,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,0-300,11.498540481074583,3,Medium,1 an,0.000973,0.513126,NaN,NaN,1.0
1395,59.356058,0.253694,18663,64.014543,0-300,11.380588736668567,3,Low,1ans,0.001038,0.547739,NaN,NaN,1.0
1396,67.865222,0.228935,19169,62.132035,501++,unknown,3,Low,1an.,0.001243,0.655622,NaN,NaN,1.0
1397,66.855435,0.244948,18946,58.697122,0-300,9.794196773761458,3,Low,1 an,0.001644,0.867537,NaN,NaN,1.0
1398,54.712713,0.177143,19017,64.259212,0-300,10.696216086742934,3,Low,1an.,0.001022,0.538969,NaN,NaN,1.0

In [56]:
#Exo 10
def transformColumnElement(dataFrame,columnName, categories):
    x = 0
    for categorie in categories:
        x+= 1
        dataFrame.loc[dataFrame[columnName]== categorie, columnName]= x
    return dataFrame[columnName].unique()

categories = ['auto-portee','electrique', 'essence']

transformColumnElement(df,"product_type", categories)

array([1, 2, 3], dtype=object)

In [47]:
#Exo 11
def transformColumnIntoCategories(dataFrame,columnName, categories):
    x = 0
    for categorie in categories:
        x+= 1
        dataFrame.loc[dataFrame[columnName]==x,categorie]=1
    return df

categories = ['auto-portee','electrique', 'essence']

transformColumnIntoCategories(df, "product_type", categories)

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness,auto-portee,electrique,essence
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,1,Low,3ans,0.006360,0.650648,1.0,NaN,NaN
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,1,Low,3 ans.,0.006840,0.699792,1.0,NaN,NaN
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,1,Low,3_ans,0.006179,0.632129,1.0,NaN,NaN
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,1,Low,3 anss,0.007925,0.810730,1.0,NaN,NaN
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,1,Medium,3ans.,0.007406,0.757614,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,3,Medium,1 an,0.000973,0.513126,NaN,NaN,1.0
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,3,Low,1ans,0.001038,0.547739,NaN,NaN,1.0
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,3,Low,1an.,0.001243,0.655622,NaN,NaN,1.0
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,3,Low,1 an,0.001644,0.867537,NaN,NaN,1.0
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,3,Low,1an.,0.001022,0.538969,NaN,NaN,1.0